# Generated by Django 3.2.9 on 2021-11-10 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0003_auto_20211110_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
    ]
