# Generated by Django 3.2.9 on 2021-11-11 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0007_alter_student_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Course',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
