# Generated by Django 3.2.9 on 2021-11-11 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0008_student_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Course',
            new_name='course',
        ),
    ]
