# Generated by Django 3.2.9 on 2021-11-11 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0009_rename_course_student_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openings.jobs')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openings.student')),
            ],
        ),
    ]
