# Generated by Django 3.2.9 on 2021-11-11 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0010_jobapplication'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='jobApplication',
            new_name='Application',
        ),
    ]
