# Generated by Django 3.2.9 on 2021-11-11 17:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0012_auto_20211111_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='required_skills',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
