# Generated by Django 3.2.9 on 2021-11-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0013_alter_jobs_required_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
