# Generated by Django 3.2.9 on 2021-11-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0018_school_reg_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='school', max_length=100, null=True),
        ),
    ]
