# Generated by Django 3.2.9 on 2021-11-12 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0019_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='official_name',
        ),
    ]
