# Generated by Django 3.2.9 on 2021-11-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0020_rename_name_user_official_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
