# Generated by Django 3.2.9 on 2021-11-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0021_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='email',
        ),
        migrations.RemoveField(
            model_name='application',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='application',
            name='attach_cv',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
