# Generated by Django 3.2.9 on 2021-11-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0024_application_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
