# Generated by Django 3.2.9 on 2021-11-14 09:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0025_jobs_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
