# Generated by Django 3.2.9 on 2021-11-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0026_alter_jobs_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='reg_no',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='reg_no',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
