# Generated by Django 3.2.9 on 2021-11-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0029_student_transcript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='transcript',
            field=models.FileField(null=True, upload_to='transcripts/'),
        ),
    ]
