# Generated by Django 3.2.9 on 2021-11-16 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0030_alter_student_transcript'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='transcript',
        ),
    ]
