# Generated by Django 3.2.9 on 2021-11-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0031_remove_student_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='transcript',
            field=models.FileField(null=True, upload_to='transcripts/'),
        ),
    ]
