# Generated by Django 3.2.9 on 2022-01-26 13:21

from django.db import migrations, models
import django.db.models.deletion
import openings.models


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0033_alter_student_transcript'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCertifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_cv', models.FileField(blank=True, null=True, upload_to=openings.models.cert_path)),
                ('upload_certifications', models.FileField(blank=True, null=True, upload_to=openings.models.cert_path)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openings.student')),
            ],
        ),
    ]
