# Generated by Django 3.2.9 on 2022-01-26 19:21

from django.db import migrations, models
import openings.models


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0035_auto_20220126_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='upload_cv',
            field=models.FileField(null=True, upload_to=openings.models.cert_path),
        ),
    ]
