# Generated by Django 3.2.9 on 2022-01-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0036_alter_application_upload_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
