# Generated by Django 3.2.9 on 2022-01-27 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0037_student_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
    ]
